version: '3.8'

networks:
  monitor-net:
    driver: bridge
    
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: retail_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_compose
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter_compose
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:password@postgres:5432/retail_db?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - monitor-net
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_compose
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    volumes:
      - ./grafana_storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=grafana_admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana_password
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_storage: