FROM tensorflow/tensorflow:1.14.0-gpu-py3

ENV DEBIAN_FRONTEND noninteractive

ARG APP_DIR=/app
WORKDIR "$APP_DIR"

ENV PYTHONPATH "${PYTHONPATH}:pwd"

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub

RUN apt-get -y update \
    && apt-get -y install python3-pip \
    && apt-get install ffmpeg libsm6 libxext6  -y \
    && apt-get install -y git \
    && pip3 install --upgrade pip

COPY requirements.txt requirements.txt

RUN pip3 install -U --no-warn-script-location -r requirements.txt --no-cache

RUN git clone -b 0.7.6 https://github.com/emedvedev/attention-ocr

RUN mv attention-ocr attention_ocr

CMD ["bash"]