app:
  yolo_model_path: "/app/best_openvino_model"
  ocr_model_path: "/app/aocr-model"

clearml:
  project_name: retail
  task_name: ${training.yolo.model_name}_training

training:
  yolo:
    dataset_path: "/app/data/data.yaml"
    image_size: 640
    epochs: 50
    batch: 16
    device: 0
  aocr:
    data_preparation:
      dataset_path: /app/ocr_ready_three_parts
      dataset_clearml_id: 
      annotations_path: ${training.aocr.data_preparation.dataset_path}/annotations-training.txt
      output_path: ${training.aocr.data_preparation.dataset_path}/training.tfrecords
      log_step: 1000
      force_uppercase: True
      save_filename: False
    phase: train # parameters.phase,
    visualize: False # parameters.visualize,
    output_dir: './results' # parameters.output_dir,
    batch_size: 65 # parameters.batch_size,
    initial_learning_rate: 1.0 #parameters.initial_learning_rate,
    steps_per_checkpoint: 200 # parameters.steps_per_checkpoint,
    model_dir: '/app/experiments/exp1' # parameters.model_dir,
    target_embedding_size: 10 # parameters.target_embedding_size,
    attn_num_hidden: 128 # parameters.attn_num_hidden,
    attn_num_layers: 2 # parameters.attn_num_layers,
    clip_gradients: True # parameters.clip_gradients,
    max_gradient_norm: 5.0 # parameters.max_gradient_norm,
    session: 
    load_model: True # parameters.load_model,
    gpu_id: 0 # parameters.gpu_id,
    use_gru: #parameters.use_gru,
    use_distance: True # parameters.use_distance,
    max_image_width: 160 # parameters.max_width, 210
    max_image_height: 60 # parameters.max_height, 80
    max_prediction_length: 8 # parameters.max_prediction, 8
    channels: 1 # parameters.channels,
    model_exporting:
      export_path: '/app/experiments/exported/exp1'
      export_format: 'savedmodel'
